language: cpp
sudo: required

os: linux
dist: xenial

env:
  global:
    - DEVKITPRO=/opt/devkitpro
    - DEVKITPPC=/opt/devkitpro/devkitPPC
    - WUT_ROOT=/opt/devkitpro/wut

matrix:
  include:
    - env: PLATFORM=wiiu
  allow_failures:
    - env: PLATFORM=wiiu

addons:
  apt:
    packages:
      - git
      - wget

install:
  - ./dependency_helper.sh

script:
  - make -f Makefile.${PLATFORM}

deploy:

  provider: releases

  skip_cleanup: true

  api_key: "d4023e375a028a7c96907ab0847607f3377e1153"

  file: appstore.rpx

  on:

    repo: lloydnabs/mk8store

    tags: false

    all_branches: true