language: cpp
sudo: required

os: linux
dist: xenial

env:
  global:
    - DEVKITPRO=/opt/devkitpro
    - DEVKITPPC=/opt/devkitpro/devkitPPC
    - WUT_ROOT=/opt/devkitpro/wut

matrix:
  include:
    - env: PLATFORM=wiiu
  allow_failures:
    - env: PLATFORM=wiiu

addons:
  apt:
    packages:
      - git
      - wget

install:
  - ./dependency_helper.sh

script:
  - make -f Makefile.${PLATFORM}

before_deploy:

- mkdir -p "wiiu/apps/mk8store"

- versiontag="0.1"

- cp appstore.rpx wiiu/apps/sdcafiine

- zip -r mk8store.zip wiiu
deploy:

  provider: releases

  skip_cleanup: true

  api_key:

    secure: "if6/uEF7XcfbNk/32Jtbr/FPObciLUPCm9mmw3Ca7RAYKsqEHr1tWM46zaMQMCJNb6W2AXtNx8rllqre8LVpPQLVCgwG+6k0y5DzLPHc+ya1tuj2sPBBvA34OTwPc+ujozhOIWjpu4vS9W+6x5NEvtRgF2jEdST2/jU4nvv4wsNlaBQiAikSh2Vfgxtu9CxeHf/1aXFhfbhoT9at2p070zoYMIbVU+3ystukREs4EixVjTQQcBRSmwNb0HJ4hBtjTR+66T/nZ6jbdWLhhu70cnnjMXs3tC7Dbrrnwy3X0Rsg7m3BMJxqmt/jIiaA0MwEd/86gNrf0H60whTgrIIKWyucrLblB0gm6WV6W5/Guh0pZ3+lPBtbLP5zWUeZFkdgex0fnGH3qdPfyq+DLih+JJgroGTsXTBQ2I0CSd6DWs+hDAF1pebqbBa/KxBBYR3gTEbd8eUFlhol1jILtffYSl8SgCF4Nvsy6hVdaW4yXw/aZAgiYzM0O7VJUiWm3hujvLBHIaZiT1xcJ+Cq280bgyna8AByuRE4Pfewfo1xUlTMDMUVmFOHsUmo1IR/5EXRji3kAVfyyfB5viurxujBCBWXYodquGJ2hExtLurVq7OaJ/RReXzHUORUEgdUFXIYtXKezZ7wfYHf0Ah55Rk1saBQcBHknnrqE8mSEsgOuiw="

  file: mk8store.zip

  on:

    repo: lloydnabs/mk8store

    tags: false

    all_branches: true