manifest = "02bd53055e1fd24871475225442c9efde237659038616c62e1a3ffb8545a1700"

[[dependency]]
package = "github.com/vgmoose/libget"
target = "//:libget"

[lock."github.com/buckaroo-pm/madler-zlib"]
versions = [ "1.2.11" ]
revision = "94a70f3274f15bf98b472178e91fd57a6e6c53d8"

[lock."github.com/buckaroo-pm/mapbox-rapidjson"]
versions = [ "branch=master" ]
revision = "44ccecfb229c4862ef4fa924a4841749196abfc7"

[lock."github.com/buckaroo-pm/nmoinvaz-minizip"]
versions = [ "1.1.0" ]
revision = "2e9b639463f3483c761ea94a14b57a253425ee1f"

[lock."github.com/buckaroo-pm/pkg-config-curl"]
versions = [ "branch=master" ]
revision = "172dabe81beabe3f4dce71d66a5ff9251ef9ef11"

[lock."github.com/vgmoose/libget"]
versions = [ "branch=master" ]
revision = "52c8cd46883a23319f1c1463011a5b40d3ab2b26"
